# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdc < Formula
  desc "Run docker compose across multiple projects"
  homepage "https://github.com/aaronflorey/multi-docker-compose"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.2.1/mdc_0.2.1_darwin_amd64.tar.gz"
      sha256 "edce64045f0c055e719925ad7800f8aa5f17dcf02e68164fb5e48d109e697551"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.2.1/mdc_0.2.1_darwin_arm64.tar.gz"
      sha256 "6ce676785257b8e74714823fc962580a90722755f895e51d201bd6180eba48ed"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.2.1/mdc_0.2.1_linux_amd64.tar.gz"
      sha256 "8f4d4af8aedb2cd8eab1ba0c2a5194a17f870f6decc7efb0b33453a096eb598c"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.2.1/mdc_0.2.1_linux_arm64.tar.gz"
      sha256 "b845413ec4294c2a562ca6a54d3a8d0ac0fa8784994f37a1b2db80f0e276a661"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  test do
    system "#{bin}/mdc", "--help"
  end
end
