# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdc < Formula
  desc "Run docker compose across multiple projects"
  homepage "https://github.com/aaronflorey/mdc"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.3.0/mdc_0.3.0_darwin_amd64.tar.gz"
      sha256 "ad2f4070f20afec5ed57219daa369dd8306b0a562cdb95ddc4b04d473e84b65a"

      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.3.0/mdc_0.3.0_darwin_arm64.tar.gz"
      sha256 "f5e29837bfbb57f4ae85e0c332c476a5263f9bcbb7ca443cb8fc1507ee26ee0c"

      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.3.0/mdc_0.3.0_linux_amd64.tar.gz"
      sha256 "162788deede0ab3e495f22ea45ddbc7b448d9e51ef8c52db72e7274c003535a8"
      define_method(:install) do
        bin.install "mdc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/mdc/releases/download/v0.3.0/mdc_0.3.0_linux_arm64.tar.gz"
      sha256 "1658f3ebea660984cdda79ea508e2e8f2a9d2342a270f704fa7b501a8ad65ff6"
      define_method(:install) do
        bin.install "mdc"
      end
    end
  end

  test do
    system "#{bin}/mdc", "--help"
  end
end
