# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StraceAnalyser < Formula
  desc "Analyze a directory of strace outputs."
  homepage "https://github.com/aaronflorey/strace-analyser"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronflorey/strace-analyser/releases/download/v0.2.0/strace-analyser_0.2.0_darwin_amd64.tar.gz"
      sha256 "7e247d8cdeb1c4c6ec7e71e3eb4494549cdea8d6fa4ae25ca4d658d7b608a48a"

      define_method(:install) do
        bin.install "strace-analyser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronflorey/strace-analyser/releases/download/v0.2.0/strace-analyser_0.2.0_darwin_arm64.tar.gz"
      sha256 "7f495f0b1f8206ba6cddf3b6939ad72a98f9042e66a4d8c53c7fda090a3e8ed3"

      define_method(:install) do
        bin.install "strace-analyser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/strace-analyser/releases/download/v0.2.0/strace-analyser_0.2.0_linux_amd64.tar.gz"
      sha256 "1c714761e8a93706e0a357bd93d81e793faa7055dcc53905a7d5ae41f5f798a9"
      define_method(:install) do
        bin.install "strace-analyser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/strace-analyser/releases/download/v0.2.0/strace-analyser_0.2.0_linux_arm64.tar.gz"
      sha256 "4319105b83686494b2962ac620748529f6c15ba0271c9e37ec02d9c9ab159b8f"
      define_method(:install) do
        bin.install "strace-analyser"
      end
    end
  end

  test do
    system "#{bin}/strace-analyser", "--help"
  end
end
