# This file was generated by GoReleaser. DO NOT EDIT.
cask "bin" do
  version "2.7.0"

  on_macos do
    on_arm do
      sha256 "1badf4b5d30e095ce86ed0c3ef82f2b75888253157cf9762b7b3567083fd5c81"
      url "https://github.com/aaronflorey/bin/releases/download/v#{version}/bin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b3cb27f82ca5be549e4a140d5ac25b6450ed4feaf759ede43ec9aba31d90ea8"
      url "https://github.com/aaronflorey/bin/releases/download/v#{version}/bin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6c824deb36258aa27fcec8afb9ce596910de558820cc5ebad4ff1d5cbfc2a297"
      url "https://github.com/aaronflorey/bin/releases/download/v#{version}/bin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4bc6ac4219cfb58941f852b722f36f7f3168eae0ef613c0ed08f2a3d02239f1f"
      url "https://github.com/aaronflorey/bin/releases/download/v#{version}/bin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bin"
  desc "Effortless binary manager - download, install, and update binaries without root"
  homepage "https://github.com/aaronflorey/bin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin"]
    end
  end

  # No zap stanza required
end
