# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-dns-sync" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "32ffabe2d40a218c64060162843518b879022dd2866e462388bb5715cb4b5ee7"
      url "https://github.com/aaronflorey/docker-dns-sync/releases/download/v#{version}/docker-dns-sync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ba86d039a986b9f98c5e0ec57ff1832f47c211fc343913af25981df0cbd1b76"
      url "https://github.com/aaronflorey/docker-dns-sync/releases/download/v#{version}/docker-dns-sync_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "165d3169e849e09659f3a8287b823106090a261af466ce65e82e1102b093c352"
      url "https://github.com/aaronflorey/docker-dns-sync/releases/download/v#{version}/docker-dns-sync_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "077491e5cb218aa675ca3516525ac05d54a35dcb4bac7464ea6a313cecf67cd1"
      url "https://github.com/aaronflorey/docker-dns-sync/releases/download/v#{version}/docker-dns-sync_#{version}_linux_amd64.tar.gz"
    end
  end

  name "docker-dns-sync"
  desc "Sync Godoxy-labeled Docker workloads into AdGuard Home rewrites"
  homepage "https://github.com/aaronflorey/docker-dns-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-dns-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-dns-sync"]
    end
  end

  # No zap stanza required
end
