# This file was generated by GoReleaser. DO NOT EDIT.
cask "mirrorselect" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/aaronflorey/ubuntu-mirrorselect/releases/download/v#{version}/mirrorselect_#{version}_darwin_amd64.tar.gz"
      sha256 "8e0938e40890cf5535c293ceabe47c8bd6d727c2afb7095f7c9037839635ff2e"
    end
    on_arm do
      url "https://github.com/aaronflorey/ubuntu-mirrorselect/releases/download/v#{version}/mirrorselect_#{version}_darwin_arm64.tar.gz"
      sha256 "1f0d3dba43d431173c648a1ddefea0cbad4758f961d8bc7531dfedaade70a237"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aaronflorey/ubuntu-mirrorselect/releases/download/v#{version}/mirrorselect_#{version}_linux_amd64.tar.gz"
      sha256 "35c647a0e57024d9738b03161ffdbb69f6669d97b5847a57158e9870cef65234"
    end
    on_arm do
      url "https://github.com/aaronflorey/ubuntu-mirrorselect/releases/download/v#{version}/mirrorselect_#{version}_linux_arm64.tar.gz"
      sha256 "5c94aee152e44e4d9cda3d92f583efb670470ec8646813e522cb4e796c3fa784"
    end
  end

  name "mirrorselect"
  desc "Select the fastest Ubuntu archive mirror by latency and download speed."
  homepage "https://github.com/aaronflorey/ubuntu-mirrorselect"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mirrorselect"

  # No zap stanza required

end
