# This file was generated by GoReleaser. DO NOT EDIT.
cask "pupdate" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "67c80c13c15cea1a200f5881e7d45e51263111d304d8d51dfe0b8790db952815"
      url "https://github.com/aaronflorey/pupdate/releases/download/v#{version}/pupdate_Darwin_x86_64.tar.gz",
        verified: "github.com/aaronflorey/pupdate/"
    end
    on_arm do
      sha256 "c003016086a3e7200a190eede0c7a860892d0fa6409efb12ee0b9921fb49bfad"
      url "https://github.com/aaronflorey/pupdate/releases/download/v#{version}/pupdate_Darwin_arm64.tar.gz",
        verified: "github.com/aaronflorey/pupdate/"
    end
  end

  on_linux do
    on_intel do
      sha256 "28b2f7a5d7712576a9ee83b40d6a78fe396fdbacb4cbb08bab668e7f7cb0e1e5"
      url "https://github.com/aaronflorey/pupdate/releases/download/v#{version}/pupdate_Linux_x86_64.tar.gz",
        verified: "github.com/aaronflorey/pupdate/"
    end
    on_arm do
      sha256 "5e27791180bfbabd25ce56f8f520de6d51be926c1318881fd3ead508166a1bf7"
      url "https://github.com/aaronflorey/pupdate/releases/download/v#{version}/pupdate_Linux_arm64.tar.gz",
        verified: "github.com/aaronflorey/pupdate/"
    end
  end

  name "pupdate"
  desc "Auto-update project dependencies on directory entry"
  homepage "https://github.com/aaronflorey/pupdate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pupdate"

  # No zap stanza required

end
