# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genignore < Formula
  desc "Generate and maintain safe .gitignore blocks"
  homepage "https://github.com/aaronflorey/genignore"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronflorey/genignore/releases/download/v1.4.0/genignore_1.4.0_darwin_amd64.tar.gz"
      sha256 "ea8c2b5c4e1bf0a906d1b7cbeafbd5edf81f33eeb42710997dc9509c33c3dcfc"

      define_method(:install) do
        bin.install "genignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronflorey/genignore/releases/download/v1.4.0/genignore_1.4.0_darwin_arm64.tar.gz"
      sha256 "7229dcd16b93527399dc9c2f10caaa395ffb66e82af48ece873ebe6794040f48"

      define_method(:install) do
        bin.install "genignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/genignore/releases/download/v1.4.0/genignore_1.4.0_linux_amd64.tar.gz"
      sha256 "41e7740a55d543471fe36a23dea4afe72a22d607570a922ee9ca5f8f252a751b"
      define_method(:install) do
        bin.install "genignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/genignore/releases/download/v1.4.0/genignore_1.4.0_linux_arm64.tar.gz"
      sha256 "c1dcb327a7633a967c54812cf06b99e414c5bdcc2776407b6a7f80222b63ad9c"
      define_method(:install) do
        bin.install "genignore"
      end
    end
  end
end
