# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pupdate < Formula
  desc "Auto-update project dependencies on directory entry"
  homepage "https://github.com/aaronflorey/pupdate"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronflorey/pupdate/releases/download/v0.3.1/pupdate_Darwin_x86_64.tar.gz"
      sha256 "a438424f064be7fb307e9794407220bb034e6ffcf9e2d8b1302731900d170a8d"

      define_method(:install) do
        bin.install "pupdate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronflorey/pupdate/releases/download/v0.3.1/pupdate_Darwin_arm64.tar.gz"
      sha256 "f1834807935eed61e6e1671fc5060b679935d579db226cf4777441ff396cda64"

      define_method(:install) do
        bin.install "pupdate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/pupdate/releases/download/v0.3.1/pupdate_Linux_x86_64.tar.gz"
      sha256 "f0faf1c2c0f3b5f8bf4073e11c7201ad07242f8c32d4d57422343b8dddc110aa"
      define_method(:install) do
        bin.install "pupdate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/pupdate/releases/download/v0.3.1/pupdate_Linux_arm64.tar.gz"
      sha256 "9f426e73b29adff3e16796037961f24f08eefd1607cab6cd96946b6f56142e2f"
      define_method(:install) do
        bin.install "pupdate"
      end
    end
  end
end
