# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnisonFsmonitor < Formula
  desc "Filesystem monitor helper for Unison"
  homepage "https://github.com/aaronflorey/unison-fsmonitor"
  version "2.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronflorey/unison-fsmonitor/releases/download/v2.0.2/unison-fsmonitor_2.0.2_darwin_amd64.tar.gz"
      sha256 "5aa069d8f98e33f98ce12e0a369dfc9d0fa398532e3fff8fa3a455d1e7886919"

      define_method(:install) do
        bin.install "unison-fsmonitor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronflorey/unison-fsmonitor/releases/download/v2.0.2/unison-fsmonitor_2.0.2_darwin_arm64.tar.gz"
      sha256 "8932a6445575bc484f74bdfd3d17489558ee1fd8ecdf975faf10da0ffb1e21af"

      define_method(:install) do
        bin.install "unison-fsmonitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/unison-fsmonitor/releases/download/v2.0.2/unison-fsmonitor_2.0.2_linux_amd64.tar.gz"
      sha256 "97dbde7c7cac8afb6e2ce758143e72cd116b1108da9195030c6b8eb4c1d89050"
      define_method(:install) do
        bin.install "unison-fsmonitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronflorey/unison-fsmonitor/releases/download/v2.0.2/unison-fsmonitor_2.0.2_linux_arm64.tar.gz"
      sha256 "ced62d0ccc060ade89a74140e080f04bab43ba78f762b88728019f778b5c38c0"
      define_method(:install) do
        bin.install "unison-fsmonitor"
      end
    end
  end
end
